spring:
  #加载banner
  output:
    ansi:
      enabled: always
      #热部署启动
    thymeleaf:
      cache: true
      devtools:
        restart:
          enabled: true
          additional-paths: src/main/java
  #配置MySQL
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://49.235.249.18:3306/seasonal?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: Guo_19980502
    driverClassName: com.mysql.cj.jdbc.Driver
  #配置Redis
  redis:
    database: 0
    timeout:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接池最大连接数（使用负值表示没有限制）
logging:
  file: E:/boot.log
  level:
    com:
      seasonal: debug
mybatis:
  type-aliases-package: com.seasonal.pojo
  configuration:
    map-underscore-to-camel-case: true